### ISSUE TITLE
Привет студентам из IT-школы Samsung! :)

### ISSUE THREAD

**Issue by jenrus00** [Dawidan-orig/ChaosPingPong#1]
![image](https://user-images.githubusercontent.com/16368461/75022429-1f529980-54a7-11ea-96ef-bfe231e23aa7.png)
Скорее всего, я забыл отвязать свой аккаунт от Android Studio, репозитории я удалю, а Павлу Валерьевичу -- привет :)

**Comment by Dawidan-orig** [comment]
ога, так и есть, только я учусь у Владимира Владимировича :D
он уже ругнулся по поводу логина, но спасибо!

пт, 21 февр. 2020 г. в 12:44, Ivan Vatlin <notifications@github.com>:
